[package]
name = "rust_bridge_header"
version = "0.1.0"
authors = ["You da author <you@da-author.app>"]
edition = "2018"

[dependencies]

[lib]
name = "rust_bridge_header"
crate-type = ["staticlib", "cdylib"]
